### ISSUE TITLE
HACS Issues

### ISSUE THREAD

**Issue by jeeftor** [TheFes/relative-time-plus#18]
<img width="647" alt="image" src="https://github.com/TheFes/relative-time-plus/assets/6491743/84ed157d-5b74-42bc-8e91-2498f34e766d">

**Comment by TheFes** [comment]
could you please give some more background? Are you trying to add it as a custom repository?
Did you already install it and are you trying to update?

**Comment by TheFes** [comment]
Note that you have to use the HACS experimental mode for custom templates

**Comment by TheFes** [comment]
Is this resolved now?

**Comment by DarthSonic** [comment]
I got this error too:
<Integration TheFes/relative-time-plus> Repository structure for v2.2.0 is not compliant
