### ISSUE TITLE
Milliseconds visible

### ISSUE THREAD

**Issue by VoyteckPL** [TheFes/relative-time-plus#29]
As these are disabled by dafault Ican still see ms for some reason. How to disable it?

**Comment by VoyteckPL** [comment]
![Screenshot_2023-11-20-19-50-55-652_io homeassistant companion android-edit](https://github.com/TheFes/relative-time-plus/assets/10666159/892d1dc4-a4ec-40dc-aef9-6e8f57b28722)
![Screenshot_2023-11-20-19-54-53-135_io homeassistant companion android-edit](https://github.com/TheFes/relative-time-plus/assets/10666159/ecd2b5a5-6995-4628-afaa-c14aeb7862d2)

**Comment by VoyteckPL** [comment]
As you can see I didn't enable milliseconds and it is visible for some reason.

**Comment by TheFes** [comment]
I'll look into it

**Comment by TheFes** [comment]
Fixed in v1.1.1

**Comment by VoyteckPL** [comment]
Nice one! Its working ok. Would that be possible to disable seconds as well? For example when I use it for last changed status I would only need minutes, hours days etc. Seconds are  not needed for me.

**Comment by TheFes** [comment]
I was already thinking of allowing to input a list with parts not to use eg
`not_use=[ 'day', 'second', 'millisecond' ]` but I, need some time to implement that

**Comment by VoyteckPL** [comment]
That is a suberb idea. Good luck buddy!

**Comment by TheFes** [comment]
should work in v1.2.0 now
https://github.com/TheFes/relative-time-plus/releases/tag/v1.2.0

**Comment by TheFes** [comment]
yeah, 7 hours :P

**Comment by VoyteckPL** [comment]
Works great. Well done!
          name: >-
            {% from 'relative_time_plus.jinja' import relative_time_plus %} {{
            relative_time_plus(states.fan.lazienka_dol.last_changed, 1,
            abbr=true,language='pl', not_use=['second', 'millisecond']) }}

**Comment by VoyteckPL** [comment]
![image](https://github.com/TheFes/relative-time-plus/assets/10666159/30891318-badc-4340-9786-d7b0b4168d83)
