### ISSUE TITLE
help with formatting the code

### ISSUE THREAD

**Issue by shift-del1** [TheFes/relative-time-plus#36]
Hello,
I'm trying to use the template macro to display the value of my HA uptime sensor. I installed manually the file and it works fine in the developer tools. It is also ok if I create a template helper and put the same format in the template section:

```
{% from 'relative_time_plus.jinja' import relative_time_plus %}
{{ relative_time_plus(states('sensor.uptime'), parts=2, not_use=['week', 'millisecond'], time=true, abbr=true, language='en') }}
```
Result is '1 hr and 35 min' in both cases. However when I try to put the code in my UI Minimalist dashboard, I can not figure out the right format:

```
- type: "custom:button-card"
  template:
    - chip_mdi_icon_state
  variables:
    ulm_chip_mdi_icon_state_entity: sensor.uptime
  label: |
    [[[
      from 'relative_time_plus.jinja' import relative_time_plus;
      return relative_time_plus(states('sensor.uptime'), parts=2, not_use=['week', 'millisecond'], time=true, abbr=true, language='en');
    ]]]
```
Can you please help me how to format the label section? Thanks in advance.

**Comment by TheFes** [comment]
Importing Jinja macros is not supported in JavaScript, which is used in these cards.
You can use a helper and display it's state

**Comment by shift-del1** [comment]
Ok, this is exactly what I did, but wanted to skip this step if possible. Now I know it is not :-) Thank you for your answer and for your macro.
