### ISSUE TITLE
miscalculation with Minutes input

### ISSUE THREAD

**Issue by fastlane086** [TheFes/relative-time-plus#4]
Hi Martijn,

my sensor, which passes the time as minutes from MQTT, apparently converts the time incorrectly with your relative_time.

I have attached a picture for you.

![relative_time_plus](https://user-images.githubusercontent.com/103284643/230944049-4f920b02-b0cb-4982-80f6-1fffe279a329.jpg)

Normally 5 days and 8 hours should come out here.

The input says 7.680 minutes

That's my code:
```
{% from 'relative_time_plus.jinja' import relative_time_plus %}
{{ relative_time_plus(states('sensor.valetudo_mistymemorablejay_main_filter'), parts=3, week=false, time=true, verbose=false, language='en') }}
```

**Comment by TheFes** [comment]
Hi,

There is no miscalculation. When a numeric value is inserted, it is interpreted as a timestamp, which means the number of seconds since 1st of January 1970.

So with your input it calculates the difference between now and a bit past 2:00 on 1st of January 1970, which is 53 years ago.

There are two possible ways to use the state you now have. I left out the optional input where you used the defaults.

Subtracting the number of minutes in your sensor from the current time
```jinja
{% from 'relative_time_plus.jinja' import relative_time_plus %} {{ relative_time_plus(now() - timedelta(minutes=states('sensor.valetudo_mistymemorablejay_main_filter')), parts=3, week=false) }}
```

Or multiply it with 60 to get the timestamp in seconds and compare that to timestamp `0`
```jinja
{% from 'relative_time_plus.jinja' import relative_time_plus %} {{ relative_time_plus(states('sensor.valetudo_mistymemorablejay_main_filter') | int * 60, parts=3, week=false, compare_date=0) }}
```

**Comment by fastlane086** [comment]
Ok thanks, it works.

![grafik](https://user-images.githubusercontent.com/103284643/231209474-2660c52f-e633-4411-b1f3-84bfe0c5f0d0.png)

**Comment by TheFes** [comment]
What is the template you are using now?

**Comment by TheFes** [comment]
Okay, and what is the state of those sensors if you look in developer tools > states?

**Comment by fastlane086** [comment]
The first four are all like this:

![grafik](https://github.com/TheFes/relative-time-plus/assets/103284643/c9fdc729-4486-49c7-95c8-8753aa229bd8)

and the last one is this:

![grafik](https://github.com/TheFes/relative-time-plus/assets/103284643/7a9a1fcc-0ce2-4ec8-929d-e50034abf2ee)

**Comment by TheFes** [comment]
You missed the breaking change that the `week` parameter is removed.
Use `not_use='week'` instead of `week=false`

**Comment by fastlane086** [comment]
It's working, thank you

![grafik](https://github.com/TheFes/relative-time-plus/assets/103284643/8d3c1f01-3be4-4efd-a167-57f1d3d608ab)

**Comment by fastlane086** [comment]
It's working, thank you

![grafik](https://github.com/TheFes/relative-time-plus/assets/103284643/8d3c1f01-3be4-4efd-a167-57f1d3d608ab)
