### ISSUE TITLE
Bug: not working anymore (typo @ line 303 + more)

### ISSUE THREAD

**Issue by Friedrieck** [TheFes/relative-time-plus#41]
There is a typo at line 303:
`always_retrun`
should read
`always_return`

But even with that solved, I still have an error:
![image](https://github.com/TheFes/relative-time-plus/assets/12567014/7240e4fc-c4f0-4970-bfaf-707e89e78d01)

**Comment by TheFes** [comment]
What was your input?

**Comment by Friedrieck** [comment]
Several variables (loop on list in attribute in a markdown card), for example with a value of `2024-03-25 09:59:56+01:00`.
Installing the former version v1.3.2 solved it for the moment.
I'm not a seasoned dev, but here https://github.com/TheFes/relative-time-plus/blob/485636929b6eb6865a1c03f6863546be746f5ba3/relative_time_plus.jinja#L322 shouldn't `error` existence be tested first (`is defined`)?

**Comment by TheFes** [comment]
Fixed in https://github.com/TheFes/relative-time-plus/releases/tag/v2.0.1
Thanks for letting me know, and spotting the typo!
