### ISSUE TITLE
Failing to render 1 part, when parts is set to 2

### ISSUE THREAD

**Issue by brechtvhb** [TheFes/relative-time-plus#60]
When I use this code

`relative_time_plus(as_local(as_datetime(states('sensor.my2024_time_to_full_charge'))),      parts=2, round_mode="common",not_use=["second", "millisecond"]) }}`

this works fine for intervals larger than 1 hour, but once it falls below one hour it shows 0 minutes instead of ,for example, 55 minutes

**Comment by brechtvhb** [comment]
Correction!
Works fine with for example an interval of 55 minutes.
It does not seem to work for an interval of 59 minutes and 50 seconds.

**Comment by TheFes** [comment]
Thanks for letting me know, I will look into it

**Comment by TheFes** [comment]
sorry it took a while, but it should be fixed now in v2.3.1

**Comment by brechtvhb** [comment]
Thanks, will check!
