### ISSUE TITLE
Formatting off somewhere

### ISSUE THREAD

**Issue by jeeftor** [TheFes/relative-time-plus#9]
<img width="640" alt="image" src="https://github.com/TheFes/relative-time-plus/assets/6491743/9d092eae-d8b4-4bb5-b3c5-18aef6da613a">

<img width="655" alt="image" src="https://github.com/TheFes/relative-time-plus/assets/6491743/3654d431-b7f6-4c42-9eab-d2e25d330171">

If i can figure out where it is i'll make a PR

**Comment by jeeftor** [comment]
Additionally removing the comment block seemed to help as well.. 🤷️

**Comment by jeeftor** [comment]
Yea I got it working o my end but always happy to share the wealth back! :)

**Comment by TheFes** [comment]
fixed in #10 by adding `-` to all opening and closing tags
